import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'user-stories',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/termux',
        'getting-started/nix-setup',
        'getting-started/updating',
        'getting-started/learning-path',
      ],
    },
    {
      type: 'category',
      label: 'Using OpenComputer',
      collapsed: true,
      items: [
        'user-guide/cli',
        'user-guide/tui',
        'user-guide/desktop',
        'user-guide/windows-native',
        'user-guide/windows-wsl-quickstart',
        'user-guide/configuration',
        'user-guide/configuring-models',
        {
          type: 'category',
          label: 'Secrets',
          collapsed: true,
          items: [
            'user-guide/secrets/index',
            'user-guide/secrets/bitwarden',
          ],
        },
        'user-guide/sessions',
        'user-guide/profiles',
        'user-guide/profile-distributions',
        'user-guide/multi-profile-gateways',
        'user-guide/git-worktrees',
        'user-guide/docker',
        'user-guide/security',
        'user-guide/checkpoints-and-rollback',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      items: [
        'user-guide/features/overview',
        'user-guide/features/tool-gateway',
        {
          type: 'category',
          label: 'Core',
          items: [
            'user-guide/features/tools',
            'user-guide/features/skills',
            'user-guide/features/lsp',
            'user-guide/features/curator',
            'user-guide/features/memory',
            'user-guide/features/memory-providers',
            'user-guide/features/honcho',
            'user-guide/features/context-files',
            'user-guide/features/context-references',
            'user-guide/features/personality',
            'user-guide/features/skins',
            'user-guide/features/plugins',
            'user-guide/features/built-in-plugins',
          ],
        },
        {
          type: 'category',
          label: 'Automation',
          items: [
            'user-guide/features/cron',
            'reference/automation-blueprints-catalog',
            'user-guide/features/delegation',
            'user-guide/features/kanban',
            'user-guide/features/codex-app-server-runtime',
            'user-guide/features/kanban-tutorial',
            'user-guide/features/kanban-worker-lanes',
            'user-guide/features/goals',
            'user-guide/features/code-execution',
            'user-guide/features/hooks',
            'user-guide/features/batch-processing',
          ],
        },
        {
          type: 'category',
          label: 'Media & Web',
          items: [
            'user-guide/features/voice-mode',
            'user-guide/features/web-search',
            'user-guide/features/x-search',
            'user-guide/features/browser',
            'user-guide/features/computer-use',
            'user-guide/features/vision',
            'user-guide/features/image-generation',
            'user-guide/features/spotify',
            'user-guide/features/tts',
            'user-guide/features/deliverable-mode',
          ],
        },
        {
          type: 'category',
          label: 'Management',
          items: [
            'user-guide/features/web-dashboard',
            'user-guide/features/extending-the-dashboard',
            'user-guide/features/api-server',
            'user-guide/features/subscription-proxy',
          ],
        },
        {
          type: 'category',
          label: 'Skills',
          collapsed: true,
          items: [
            'reference/skills-catalog',
            'reference/optional-skills-catalog',
            {
              type: 'category',
              label: 'Bundled',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'agent-eval',
                  key: 'skills-bundled-agent-eval',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/agent-eval/agent-eval-agent-eval',
                  ],
                },
                {
                  type: 'category',
                  label: 'apple',
                  key: 'skills-bundled-apple',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/apple/apple-apple-notes',
                    'user-guide/skills/bundled/apple/apple-apple-reminders',
                    'user-guide/skills/bundled/apple/apple-findmy',
                    'user-guide/skills/bundled/apple/apple-imessage',
                    'user-guide/skills/bundled/apple/apple-macos-computer-use',
                  ],
                },
                {
                  type: 'category',
                  label: 'autonomous-ai-agents',
                  key: 'skills-bundled-autonomous-ai-agents',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-claude-code',
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-codex',
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-opencode',
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-opencomputer-agent',
                  ],
                },
                {
                  type: 'category',
                  label: 'browser-control',
                  key: 'skills-bundled-browser-control',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/browser-control/browser-control-browser-control',
                  ],
                },
                {
                  type: 'category',
                  label: 'bundles-manage',
                  key: 'skills-bundled-bundles-manage',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/bundles-manage/bundles-manage-bundles-manage',
                  ],
                },
                {
                  type: 'category',
                  label: 'creative',
                  key: 'skills-bundled-creative',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/creative/creative-algorithmic-art',
                    'user-guide/skills/bundled/creative/creative-architecture-diagram',
                    'user-guide/skills/bundled/creative/creative-ascii-art',
                    'user-guide/skills/bundled/creative/creative-ascii-video',
                    'user-guide/skills/bundled/creative/creative-baoyu-infographic',
                    'user-guide/skills/bundled/creative/creative-brand-guidelines',
                    'user-guide/skills/bundled/creative/creative-canvas-design',
                    'user-guide/skills/bundled/creative/creative-claude-design',
                    'user-guide/skills/bundled/creative/creative-comfyui',
                    'user-guide/skills/bundled/creative/creative-design-md',
                    'user-guide/skills/bundled/creative/creative-excalidraw',
                    'user-guide/skills/bundled/creative/creative-humanizer',
                    'user-guide/skills/bundled/creative/creative-manim-video',
                    'user-guide/skills/bundled/creative/creative-p5js',
                    'user-guide/skills/bundled/creative/creative-popular-web-designs',
                    'user-guide/skills/bundled/creative/creative-pretext',
                    'user-guide/skills/bundled/creative/creative-sketch',
                    'user-guide/skills/bundled/creative/creative-songwriting-and-ai-music',
                    'user-guide/skills/bundled/creative/creative-theme-factory',
                    'user-guide/skills/bundled/creative/creative-touchdesigner-mcp',
                  ],
                },
                {
                  type: 'category',
                  label: 'cron-scheduling',
                  key: 'skills-bundled-cron-scheduling',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/cron-scheduling/cron-scheduling-cron-scheduling',
                  ],
                },
                {
                  type: 'category',
                  label: 'curator-maintenance',
                  key: 'skills-bundled-curator-maintenance',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/curator-maintenance/curator-maintenance-curator-maintenance',
                  ],
                },
                {
                  type: 'category',
                  label: 'data-science',
                  key: 'skills-bundled-data-science',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/data-science/data-science-jupyter-live-kernel',
                  ],
                },
                {
                  type: 'category',
                  label: 'devops',
                  key: 'skills-bundled-devops',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/devops/devops-kanban-orchestrator',
                    'user-guide/skills/bundled/devops/devops-kanban-worker',
                  ],
                },
                {
                  type: 'category',
                  label: 'dogfood',
                  key: 'skills-bundled-dogfood',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/dogfood/dogfood-dogfood',
                  ],
                },
                {
                  type: 'category',
                  label: 'dreaming',
                  key: 'skills-bundled-dreaming',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/dreaming/dreaming-dreaming',
                  ],
                },
                {
                  type: 'category',
                  label: 'email',
                  key: 'skills-bundled-email',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/email/email-himalaya',
                  ],
                },
                {
                  type: 'category',
                  label: 'finance',
                  key: 'skills-bundled-finance',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/finance/finance-3-statement-model',
                    'user-guide/skills/bundled/finance/finance-accrual-schedule',
                    'user-guide/skills/bundled/finance/finance-ai-readiness',
                    'user-guide/skills/bundled/finance/finance-audit-xls',
                    'user-guide/skills/bundled/finance/finance-bond-futures-basis',
                    'user-guide/skills/bundled/finance/finance-bond-relative-value',
                    'user-guide/skills/bundled/finance/finance-break-trace',
                    'user-guide/skills/bundled/finance/finance-buyer-list',
                    'user-guide/skills/bundled/finance/finance-catalyst-calendar',
                    'user-guide/skills/bundled/finance/finance-cim-builder',
                    'user-guide/skills/bundled/finance/finance-clean-data-xls',
                    'user-guide/skills/bundled/finance/finance-client-report',
                    'user-guide/skills/bundled/finance/finance-client-review',
                    'user-guide/skills/bundled/finance/finance-competitive-analysis',
                    'user-guide/skills/bundled/finance/finance-comps-analysis',
                    'user-guide/skills/bundled/finance/finance-datapack-builder',
                    'user-guide/skills/bundled/finance/finance-dcf-model',
                    'user-guide/skills/bundled/finance/finance-dd-checklist',
                    'user-guide/skills/bundled/finance/finance-dd-meeting-prep',
                    'user-guide/skills/bundled/finance/finance-deal-screening',
                    'user-guide/skills/bundled/finance/finance-deal-sourcing',
                    'user-guide/skills/bundled/finance/finance-deal-tracker',
                    'user-guide/skills/bundled/finance/finance-deck-refresh',
                    'user-guide/skills/bundled/finance/finance-earnings-analysis',
                    'user-guide/skills/bundled/finance/finance-earnings-preview',
                    'user-guide/skills/bundled/finance/finance-earnings-preview-beta',
                    'user-guide/skills/bundled/finance/finance-equity-research',
                    'user-guide/skills/bundled/finance/finance-financial-plan',
                    'user-guide/skills/bundled/finance/finance-fixed-income-portfolio',
                    'user-guide/skills/bundled/finance/finance-funding-digest',
                    'user-guide/skills/bundled/finance/finance-fx-carry-trade',
                    'user-guide/skills/bundled/finance/finance-gl-recon',
                    'user-guide/skills/bundled/finance/finance-ib-check-deck',
                    'user-guide/skills/bundled/finance/finance-ic-memo',
                    'user-guide/skills/bundled/finance/finance-idea-generation',
                    'user-guide/skills/bundled/finance/finance-initiating-coverage',
                    'user-guide/skills/bundled/finance/finance-investment-proposal',
                    'user-guide/skills/bundled/finance/finance-kyc-doc-parse',
                    'user-guide/skills/bundled/finance/finance-kyc-rules',
                    'user-guide/skills/bundled/finance/finance-lbo-model',
                    'user-guide/skills/bundled/finance/finance-macro-rates-monitor',
                    'user-guide/skills/bundled/finance/finance-merger-model',
                    'user-guide/skills/bundled/finance/finance-model-update',
                    'user-guide/skills/bundled/finance/finance-morning-note',
                    'user-guide/skills/bundled/finance/finance-nav-tieout',
                    'user-guide/skills/bundled/finance/finance-option-vol-analysis',
                    'user-guide/skills/bundled/finance/finance-pitch-deck',
                    'user-guide/skills/bundled/finance/finance-portfolio-monitoring',
                    'user-guide/skills/bundled/finance/finance-portfolio-rebalance',
                    'user-guide/skills/bundled/finance/finance-ppt-template-creator',
                    'user-guide/skills/bundled/finance/finance-pptx-author',
                    'user-guide/skills/bundled/finance/finance-process-letter',
                    'user-guide/skills/bundled/finance/finance-returns-analysis',
                    'user-guide/skills/bundled/finance/finance-roll-forward',
                    'user-guide/skills/bundled/finance/finance-sector-overview',
                    'user-guide/skills/bundled/finance/finance-strip-profile',
                    'user-guide/skills/bundled/finance/finance-swap-curve-strategy',
                    'user-guide/skills/bundled/finance/finance-tax-loss-harvesting',
                    'user-guide/skills/bundled/finance/finance-tear-sheet',
                    'user-guide/skills/bundled/finance/finance-teaser',
                    'user-guide/skills/bundled/finance/finance-thesis-tracker',
                    'user-guide/skills/bundled/finance/finance-unit-economics',
                    'user-guide/skills/bundled/finance/finance-value-creation-plan',
                    'user-guide/skills/bundled/finance/finance-variance-commentary',
                    'user-guide/skills/bundled/finance/finance-xlsx-author',
                  ],
                },
                {
                  type: 'category',
                  label: 'gateway-control',
                  key: 'skills-bundled-gateway-control',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/gateway-control/gateway-control-gateway-control',
                  ],
                },
                {
                  type: 'category',
                  label: 'github',
                  key: 'skills-bundled-github',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/github/github-codebase-inspection',
                    'user-guide/skills/bundled/github/github-github-auth',
                    'user-guide/skills/bundled/github/github-github-code-review',
                    'user-guide/skills/bundled/github/github-github-issues',
                    'user-guide/skills/bundled/github/github-github-pr-workflow',
                    'user-guide/skills/bundled/github/github-github-repo-management',
                  ],
                },
                {
                  type: 'category',
                  label: 'intent-dispatcher',
                  key: 'skills-bundled-intent-dispatcher',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/intent-dispatcher/intent-dispatcher-intent-dispatcher',
                  ],
                },
                {
                  type: 'category',
                  label: 'knowledge-work',
                  key: 'skills-bundled-knowledge-work',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-design-accessibility-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-common-room-account-research',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-account-research',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-analyze',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-contact-center-android',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-android',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-android',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-virtual-agent-android',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-pdf-viewer-commands-annotate',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-architecture',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-finance-audit-support',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-commands-brainstorm',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-marketing-brand-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-brand-voice-brand-voice-enforcement',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-brief',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-build-dashboard',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-build-zoom-bot',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-build-zoom-meeting-app',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-business-pulse',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-call-list',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-common-room-call-prep',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-call-prep',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-call-summary',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-marketing-campaign-plan',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-canva-creator',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-capacity-plan',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-cash-flow-snapshot',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-change-request',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-slack-commands-channel-digest',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-choose-zoom-approach',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-web-client-view',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-finance-close-management',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-close-month',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-cobrowse-sdk',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-code-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-comp-analysis',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-marketing-competitive-brief',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-competitive-brief',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-competitive-intelligence',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-compliance-check',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-compliance-tracking',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-web-component-view',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-common-room-compose-outreach',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-contact-center',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-common-room-contact-research',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-marketing-content-creation',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-content-strategy',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-contract-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-cowork-plugin-management-cowork-plugin-customizer',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-create-an-asset',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-cowork-plugin-management-create-cowork-plugin',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-create-viz',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-crm-cleanup',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-crm-maintenance',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-customer-support-customer-escalation',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-customer-pulse',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-customer-pulse-check',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-customer-support-customer-research',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-daily-briefing',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-data-context-extractor',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-data-visualization',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-debug',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-debug-zoom',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-debug-zoom-integration',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-deploy-checklist',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-design-design-critique',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-design-design-handoff',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-design-mcp-workflow',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-design-design-system',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-enterprise-search-digest',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-brand-voice-commands-discover-brand',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-brand-voice-discover-brand',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-documentation',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-slack-commands-draft-announcement',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-marketing-draft-content',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-draft-offer',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-draft-outreach',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-customer-support-draft-response',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-electron',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-marketing-email-sequence',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-brand-voice-commands-enforce-voice',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-apollo-enrich-lead',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-explore-data',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-pdf-viewer-commands-fill-form',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-finance-financial-statements',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-slack-commands-find-discussions',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-flutter',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-forecast',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-friday-brief',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-general',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-common-room-commands-generate-account-plan',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-brand-voice-commands-generate-guidelines',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-brand-voice-guideline-generation',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-handle-complaint',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-incident-response',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-bio-research-instrument-data-to-allotrope',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-interview-prep',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-invoice-chase',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-contact-center-ios',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-ios',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-ios',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-virtual-agent-ios',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-job-post-builder',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-finance-journal-entry',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-finance-journal-entry-prep',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-customer-support-kb-article',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-enterprise-search-knowledge-synthesis',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-lead-triage',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-legal-response',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-legal-risk-assessment',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-linux',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-linux',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-macos',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-macos',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-margin-analyzer',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-meeting-briefing',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-productivity-memory-management',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-metrics-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-monday-brief',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-month-end-prep',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-month-heads-up',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-bio-research-nextflow-development',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-oauth',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-onboarding',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-pdf-viewer-commands-open',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-org-planning',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-people-report',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-marketing-performance-report',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-performance-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-phone',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-sales-pipeline-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-plan-payroll',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-plan-zoom-integration',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-plan-zoom-product',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-policy-lookup',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-price-check',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-probe-sdk',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-process-doc',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-process-optimization',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-product-brainstorming',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-apollo-prospect',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-common-room-prospect',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-quarterly-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-react-native',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-react-native',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-finance-reconciliation',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-human-resources-recruiting-pipeline',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-design-research-synthesis',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-rest-api',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-review-contract',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-review-contract',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-risk-assessment',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-rivet-sdk',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-roadmap-update',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-rtms',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-run-campaign',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-runbook',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-sales-brief',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-bio-research-scientific-problem-selection',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-scribe',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-bio-research-scvi-tools',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-enterprise-search-search',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-enterprise-search-search-strategy',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-marketing-seo-audit',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-apollo-sequence-load',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-setup-zoom-mcp',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-setup-zoom-oauth',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-pdf-viewer-commands-sign',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-signature-request',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-bio-research-single-cell-rna-qc',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-slack-slack-messaging',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-slack-slack-search',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-smb-onboard',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-smb-router',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-enterprise-search-source-management',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-finance-sox-testing',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-sprint-planning',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-sql-queries',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-stakeholder-update',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-standup',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-slack-commands-standup',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-bio-research-start',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-start',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-productivity-start',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-statistical-analysis',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-status-report',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-slack-commands-summarize-channel',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-synthesize-research',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-system-design',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-productivity-task-management',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-tax-prep',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-tax-season-organizer',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-team-chat',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-tech-debt',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-engineering-testing-strategy',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-small-business-ticket-deflector',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-customer-support-ticket-triage',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-triage-nda',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-ui-toolkit',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-unity',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-unreal',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-productivity-update',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-design-user-research',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-design-ux-copy',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-validate-data',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-finance-variance-analysis',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-legal-vendor-check',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-operations-vendor-review',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-pdf-viewer-view-pdf',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-virtual-agent',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-contact-center-web',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-web',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-web',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-virtual-agent-web',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-webhooks',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-websockets',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-common-room-commands-weekly-brief',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-common-room-weekly-prep-brief',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-zoom-mcp-whiteboard',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-meeting-sdk-windows',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-video-sdk-windows',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-data-write-query',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-product-management-write-spec',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-zoom-apps-sdk',
                    'user-guide/skills/bundled/knowledge-work/knowledge-work-partner-built-zoom-plugin-zoom-mcp',
                  ],
                },
                {
                  type: 'category',
                  label: 'legal',
                  key: 'skills-bundled-legal',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/legal/legal-ai-governance-legal-ai-inventory',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-ai-tool-handoff',
                    'user-guide/skills/bundled/legal/legal-ai-governance-legal-aia-generation',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-amendment-history',
                    'user-guide/skills/bundled/legal/legal-law-student-bar-prep-questions',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-board-minutes',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-brief-section-drafter',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-build-guide',
                    'user-guide/skills/bundled/legal/legal-law-student-case-brief',
                    'user-guide/skills/bundled/legal/legal-ip-legal-cease-desist',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-chronology',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-claim-chart',
                    'user-guide/skills/bundled/legal/legal-ip-legal-clearance',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-client-comms-log',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-client-intake',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-client-letter',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-closing-checklist',
                    'user-guide/skills/bundled/legal/legal-law-student-cold-call-prep',
                    'user-guide/skills/bundled/legal/legal-regulatory-legal-comments',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-deadlines',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-deal-team-summary',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-demand-draft',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-demand-intake',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-demand-received',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-deposition-prep',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-diligence-issue-extraction',
                    'user-guide/skills/bundled/legal/legal-privacy-legal-dpa-review',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-draft',
                    'user-guide/skills/bundled/legal/legal-privacy-legal-dsar-response',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-entity-compliance',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-escalation-flagger',
                    'user-guide/skills/bundled/legal/legal-law-student-exam-forecast',
                    'user-guide/skills/bundled/legal/legal-employment-legal-expansion-kickoff',
                    'user-guide/skills/bundled/legal/legal-employment-legal-expansion-update',
                    'user-guide/skills/bundled/legal/legal-product-legal-feature-risk-assessment',
                    'user-guide/skills/bundled/legal/legal-law-student-flashcards',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-form-generation',
                    'user-guide/skills/bundled/legal/legal-ip-legal-fto-triage',
                    'user-guide/skills/bundled/legal/legal-regulatory-legal-gap-surfacer',
                    'user-guide/skills/bundled/legal/legal-regulatory-legal-gaps',
                    'user-guide/skills/bundled/legal/legal-employment-legal-handbook-updates',
                    'user-guide/skills/bundled/legal/legal-employment-legal-hiring-review',
                    'user-guide/skills/bundled/legal/legal-ip-legal-infringement-triage',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-integration-management',
                    'user-guide/skills/bundled/legal/legal-employment-legal-internal-investigation',
                    'user-guide/skills/bundled/legal/legal-employment-legal-international-expansion',
                    'user-guide/skills/bundled/legal/legal-ip-legal-invention-intake',
                    'user-guide/skills/bundled/legal/legal-employment-legal-investigation-add',
                    'user-guide/skills/bundled/legal/legal-employment-legal-investigation-memo',
                    'user-guide/skills/bundled/legal/legal-employment-legal-investigation-open',
                    'user-guide/skills/bundled/legal/legal-employment-legal-investigation-query',
                    'user-guide/skills/bundled/legal/legal-employment-legal-investigation-summary',
                    'user-guide/skills/bundled/legal/legal-ip-legal-ip-clause-review',
                    'user-guide/skills/bundled/legal/legal-law-student-irac-practice',
                    'user-guide/skills/bundled/legal/legal-product-legal-is-this-a-problem',
                    'user-guide/skills/bundled/legal/legal-product-legal-launch-review',
                    'user-guide/skills/bundled/legal/legal-employment-legal-leave-tracker',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-legal-hold',
                    'user-guide/skills/bundled/legal/legal-law-student-legal-writing',
                    'user-guide/skills/bundled/legal/legal-employment-legal-log-leave',
                    'user-guide/skills/bundled/legal/legal-product-legal-marketing-claims-review',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-material-contract-schedule',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-matter-briefing',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-matter-close',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-matter-intake',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-matter-update',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-memo',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-nda-review',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-oc-status',
                    'user-guide/skills/bundled/legal/legal-ip-legal-oss-review',
                    'user-guide/skills/bundled/legal/legal-law-student-outline-builder',
                    'user-guide/skills/bundled/legal/legal-privacy-legal-pia-generation',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-plain-language-letters',
                    'user-guide/skills/bundled/legal/legal-regulatory-legal-policy-diff',
                    'user-guide/skills/bundled/legal/legal-employment-legal-policy-drafting',
                    'user-guide/skills/bundled/legal/legal-ai-governance-legal-policy-monitor',
                    'user-guide/skills/bundled/legal/legal-privacy-legal-policy-monitor',
                    'user-guide/skills/bundled/legal/legal-regulatory-legal-policy-redraft',
                    'user-guide/skills/bundled/legal/legal-ai-governance-legal-policy-starter',
                    'user-guide/skills/bundled/legal/legal-ip-legal-portfolio',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-portfolio-status',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-privilege-log-review',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-ramp',
                    'user-guide/skills/bundled/legal/legal-regulatory-legal-reg-feed-watcher',
                    'user-guide/skills/bundled/legal/legal-ai-governance-legal-reg-gap-analysis',
                    'user-guide/skills/bundled/legal/legal-privacy-legal-reg-gap-analysis',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-renewal-tracker',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-research-start',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-review',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-review-proposals',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-saas-msa-review',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-semester-handoff',
                    'user-guide/skills/bundled/legal/legal-law-student-session',
                    'user-guide/skills/bundled/legal/legal-law-student-socratic-drill',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-stakeholder-summary',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-status',
                    'user-guide/skills/bundled/legal/legal-law-student-study-plan',
                    'user-guide/skills/bundled/legal/legal-litigation-legal-subpoena-triage',
                    'user-guide/skills/bundled/legal/legal-legal-clinic-supervisor-review-queue',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-tabular-review',
                    'user-guide/skills/bundled/legal/legal-ip-legal-takedown',
                    'user-guide/skills/bundled/legal/legal-employment-legal-termination-review',
                    'user-guide/skills/bundled/legal/legal-ai-governance-legal-use-case-triage',
                    'user-guide/skills/bundled/legal/legal-privacy-legal-use-case-triage',
                    'user-guide/skills/bundled/legal/legal-commercial-legal-vendor-agreement-review',
                    'user-guide/skills/bundled/legal/legal-ai-governance-legal-vendor-ai-review',
                    'user-guide/skills/bundled/legal/legal-employment-legal-wage-hour-qa',
                    'user-guide/skills/bundled/legal/legal-employment-legal-worker-classification',
                    'user-guide/skills/bundled/legal/legal-corporate-legal-written-consent',
                  ],
                },
                {
                  type: 'category',
                  label: 'media',
                  key: 'skills-bundled-media',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/media/media-gif-search',
                    'user-guide/skills/bundled/media/media-heartmula',
                    'user-guide/skills/bundled/media/media-slack-gif-creator',
                    'user-guide/skills/bundled/media/media-songsee',
                    'user-guide/skills/bundled/media/media-youtube-content',
                  ],
                },
                {
                  type: 'category',
                  label: 'memory-manage',
                  key: 'skills-bundled-memory-manage',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/memory-manage/memory-manage-memory-manage',
                  ],
                },
                {
                  type: 'category',
                  label: 'mermaid-maker',
                  key: 'skills-bundled-mermaid-maker',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/mermaid-maker/mermaid-maker-mermaid-maker',
                  ],
                },
                {
                  type: 'category',
                  label: 'mlops',
                  key: 'skills-bundled-mlops',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/mlops/mlops-models-audiocraft',
                    'user-guide/skills/bundled/mlops/mlops-huggingface-hub',
                    'user-guide/skills/bundled/mlops/mlops-inference-llama-cpp',
                    'user-guide/skills/bundled/mlops/mlops-evaluation-lm-evaluation-harness',
                    'user-guide/skills/bundled/mlops/mlops-models-segment-anything',
                    'user-guide/skills/bundled/mlops/mlops-inference-vllm',
                    'user-guide/skills/bundled/mlops/mlops-evaluation-weights-and-biases',
                  ],
                },
                {
                  type: 'category',
                  label: 'note-taking',
                  key: 'skills-bundled-note-taking',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/note-taking/note-taking-obsidian',
                  ],
                },
                {
                  type: 'category',
                  label: 'parallel-agents',
                  key: 'skills-bundled-parallel-agents',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/parallel-agents/parallel-agents-parallel-agents',
                  ],
                },
                {
                  type: 'category',
                  label: 'productivity',
                  key: 'skills-bundled-productivity',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/productivity/productivity-airtable',
                    'user-guide/skills/bundled/productivity/productivity-doc-coauthoring',
                    'user-guide/skills/bundled/productivity/productivity-docx',
                    'user-guide/skills/bundled/productivity/productivity-google-workspace',
                    'user-guide/skills/bundled/productivity/productivity-internal-comms',
                    'user-guide/skills/bundled/productivity/productivity-maps',
                    'user-guide/skills/bundled/productivity/productivity-nano-pdf',
                    'user-guide/skills/bundled/productivity/productivity-notion',
                    'user-guide/skills/bundled/productivity/productivity-ocr-and-documents',
                    'user-guide/skills/bundled/productivity/productivity-pdf',
                    'user-guide/skills/bundled/productivity/productivity-powerpoint',
                    'user-guide/skills/bundled/productivity/productivity-pptx',
                    'user-guide/skills/bundled/productivity/productivity-teams-meeting-pipeline',
                    'user-guide/skills/bundled/productivity/productivity-xlsx',
                  ],
                },
                {
                  type: 'category',
                  label: 'profiles-manage',
                  key: 'skills-bundled-profiles-manage',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/profiles-manage/profiles-manage-profiles-manage',
                  ],
                },
                {
                  type: 'category',
                  label: 'project-memory',
                  key: 'skills-bundled-project-memory',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/project-memory/project-memory-project-memory',
                  ],
                },
                {
                  type: 'category',
                  label: 'prompt-optimization',
                  key: 'skills-bundled-prompt-optimization',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/prompt-optimization/prompt-optimization-prompt-optimization',
                  ],
                },
                {
                  type: 'category',
                  label: 'research',
                  key: 'skills-bundled-research',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/research/research-arxiv',
                    'user-guide/skills/bundled/research/research-blogwatcher',
                    'user-guide/skills/bundled/research/research-competitor-analysis',
                    'user-guide/skills/bundled/research/research-deep-research',
                    'user-guide/skills/bundled/research/research-llm-wiki',
                    'user-guide/skills/bundled/research/research-polymarket',
                    'user-guide/skills/bundled/research/research-research-paper-writing',
                    'user-guide/skills/bundled/research/research-storm',
                  ],
                },
                {
                  type: 'category',
                  label: 'reset-safe-memory',
                  key: 'skills-bundled-reset-safe-memory',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/reset-safe-memory/reset-safe-memory-reset-safe-memory',
                  ],
                },
                {
                  type: 'category',
                  label: 'silent-failure-hunter',
                  key: 'skills-bundled-silent-failure-hunter',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/silent-failure-hunter/silent-failure-hunter-silent-failure-hunter',
                  ],
                },
                {
                  type: 'category',
                  label: 'skill-router',
                  key: 'skills-bundled-skill-router',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/skill-router/skill-router-skill-router',
                  ],
                },
                {
                  type: 'category',
                  label: 'skill-security-scan',
                  key: 'skills-bundled-skill-security-scan',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/skill-security-scan/skill-security-scan-skill-security-scan',
                  ],
                },
                {
                  type: 'category',
                  label: 'skills-manage',
                  key: 'skills-bundled-skills-manage',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/skills-manage/skills-manage-skills-manage',
                  ],
                },
                {
                  type: 'category',
                  label: 'smart-home',
                  key: 'skills-bundled-smart-home',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/smart-home/smart-home-openhue',
                  ],
                },
                {
                  type: 'category',
                  label: 'social-media',
                  key: 'skills-bundled-social-media',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/social-media/social-media-xurl',
                  ],
                },
                {
                  type: 'category',
                  label: 'software-development',
                  key: 'skills-bundled-software-development',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/software-development/software-development-accessibility-audit',
                    'user-guide/skills/bundled/software-development/software-development-api-and-interface-design',
                    'user-guide/skills/bundled/software-development/software-development-ci-cd-and-automation',
                    'user-guide/skills/bundled/software-development/software-development-claude-api',
                    'user-guide/skills/bundled/software-development/software-development-context-engineering',
                    'user-guide/skills/bundled/software-development/software-development-deprecation-and-migration',
                    'user-guide/skills/bundled/software-development/software-development-documentation-and-adrs',
                    'user-guide/skills/bundled/software-development/software-development-doubt-driven-development',
                    'user-guide/skills/bundled/software-development/software-development-frontend-design',
                    'user-guide/skills/bundled/software-development/software-development-frontend-ui-engineering',
                    'user-guide/skills/bundled/software-development/software-development-git-workflow-and-versioning',
                    'user-guide/skills/bundled/software-development/software-development-idea-refine',
                    'user-guide/skills/bundled/software-development/software-development-incremental-implementation',
                    'user-guide/skills/bundled/software-development/software-development-interview-me',
                    'user-guide/skills/bundled/software-development/software-development-mcp-builder',
                    'user-guide/skills/bundled/software-development/software-development-node-inspect-debugger',
                    'user-guide/skills/bundled/software-development/software-development-observability-and-instrumentation',
                    'user-guide/skills/bundled/software-development/software-development-opencomputer-skill-authoring',
                    'user-guide/skills/bundled/software-development/software-development-performance-optimization',
                    'user-guide/skills/bundled/software-development/software-development-plan',
                    'user-guide/skills/bundled/software-development/software-development-python-debugpy',
                    'user-guide/skills/bundled/software-development/software-development-requesting-code-review',
                    'user-guide/skills/bundled/software-development/software-development-security-and-hardening',
                    'user-guide/skills/bundled/software-development/software-development-shipping-and-launch',
                    'user-guide/skills/bundled/software-development/software-development-simplify-code',
                    'user-guide/skills/bundled/software-development/software-development-skill-creator',
                    'user-guide/skills/bundled/software-development/software-development-source-driven-development',
                    'user-guide/skills/bundled/software-development/software-development-spec-driven-development',
                    'user-guide/skills/bundled/software-development/software-development-spike',
                    'user-guide/skills/bundled/software-development/software-development-systematic-debugging',
                    'user-guide/skills/bundled/software-development/software-development-test-driven-development',
                    'user-guide/skills/bundled/software-development/software-development-web-artifacts-builder',
                    'user-guide/skills/bundled/software-development/software-development-webapp-testing',
                  ],
                },
                {
                  type: 'category',
                  label: 'soul-grader',
                  key: 'skills-bundled-soul-grader',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/soul-grader/soul-grader-soul-grader',
                  ],
                },
                {
                  type: 'category',
                  label: 'verification-before-completion',
                  key: 'skills-bundled-verification-before-completion',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/verification-before-completion/verification-before-completion-verification-before-completion',
                  ],
                },
                {
                  type: 'category',
                  label: 'yuanbao',
                  key: 'skills-bundled-yuanbao',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/yuanbao/yuanbao-yuanbao',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Optional',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'autonomous-ai-agents',
                  key: 'skills-optional-autonomous-ai-agents',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-antigravity-cli',
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-blackbox',
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-grok',
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-honcho',
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-openhands',
                  ],
                },
                {
                  type: 'category',
                  label: 'blockchain',
                  key: 'skills-optional-blockchain',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/blockchain/blockchain-evm',
                    'user-guide/skills/optional/blockchain/blockchain-hyperliquid',
                    'user-guide/skills/optional/blockchain/blockchain-solana',
                  ],
                },
                {
                  type: 'category',
                  label: 'communication',
                  key: 'skills-optional-communication',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/communication/communication-one-three-one-rule',
                  ],
                },
                {
                  type: 'category',
                  label: 'creative',
                  key: 'skills-optional-creative',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/creative/creative-baoyu-article-illustrator',
                    'user-guide/skills/optional/creative/creative-baoyu-comic',
                    'user-guide/skills/optional/creative/creative-blender-mcp',
                    'user-guide/skills/optional/creative/creative-concept-diagrams',
                    'user-guide/skills/optional/creative/creative-creative-ideation',
                    'user-guide/skills/optional/creative/creative-hyperframes',
                    'user-guide/skills/optional/creative/creative-kanban-video-orchestrator',
                    'user-guide/skills/optional/creative/creative-meme-generation',
                    'user-guide/skills/optional/creative/creative-pixel-art',
                  ],
                },
                {
                  type: 'category',
                  label: 'devops',
                  key: 'skills-optional-devops',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/devops/devops-cli',
                    'user-guide/skills/optional/devops/devops-docker-management',
                    'user-guide/skills/optional/devops/devops-opencomputer-s6-container-supervision',
                    'user-guide/skills/optional/devops/devops-pinggy-tunnel',
                    'user-guide/skills/optional/devops/devops-watchers',
                  ],
                },
                {
                  type: 'category',
                  label: 'dogfood',
                  key: 'skills-optional-dogfood',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/dogfood/dogfood-adversarial-ux-test',
                  ],
                },
                {
                  type: 'category',
                  label: 'email',
                  key: 'skills-optional-email',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/email/email-agentmail',
                  ],
                },
                {
                  type: 'category',
                  label: 'finance',
                  key: 'skills-optional-finance',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/finance/finance-3-statement-model',
                    'user-guide/skills/optional/finance/finance-comps-analysis',
                    'user-guide/skills/optional/finance/finance-dcf-model',
                    'user-guide/skills/optional/finance/finance-excel-author',
                    'user-guide/skills/optional/finance/finance-lbo-model',
                    'user-guide/skills/optional/finance/finance-merger-model',
                    'user-guide/skills/optional/finance/finance-pptx-author',
                    'user-guide/skills/optional/finance/finance-stocks',
                  ],
                },
                {
                  type: 'category',
                  label: 'gaming',
                  key: 'skills-optional-gaming',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/gaming/gaming-minecraft-modpack-server',
                    'user-guide/skills/optional/gaming/gaming-pokemon-player',
                  ],
                },
                {
                  type: 'category',
                  label: 'health',
                  key: 'skills-optional-health',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/health/health-fitness-nutrition',
                    'user-guide/skills/optional/health/health-neuroskill-bci',
                  ],
                },
                {
                  type: 'category',
                  label: 'mcp',
                  key: 'skills-optional-mcp',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/mcp/mcp-fastmcp',
                    'user-guide/skills/optional/mcp/mcp-mcporter',
                  ],
                },
                {
                  type: 'category',
                  label: 'migration',
                  key: 'skills-optional-migration',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/migration/migration-openclaw-migration',
                  ],
                },
                {
                  type: 'category',
                  label: 'mlops',
                  key: 'skills-optional-mlops',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/mlops/mlops-accelerate',
                    'user-guide/skills/optional/mlops/mlops-training-axolotl',
                    'user-guide/skills/optional/mlops/mlops-chroma',
                    'user-guide/skills/optional/mlops/mlops-clip',
                    'user-guide/skills/optional/mlops/mlops-research-dspy',
                    'user-guide/skills/optional/mlops/mlops-faiss',
                    'user-guide/skills/optional/mlops/mlops-flash-attention',
                    'user-guide/skills/optional/mlops/mlops-guidance',
                    'user-guide/skills/optional/mlops/mlops-huggingface-tokenizers',
                    'user-guide/skills/optional/mlops/mlops-instructor',
                    'user-guide/skills/optional/mlops/mlops-lambda-labs',
                    'user-guide/skills/optional/mlops/mlops-llava',
                    'user-guide/skills/optional/mlops/mlops-modal',
                    'user-guide/skills/optional/mlops/mlops-nemo-curator',
                    'user-guide/skills/optional/mlops/mlops-inference-outlines',
                    'user-guide/skills/optional/mlops/mlops-peft',
                    'user-guide/skills/optional/mlops/mlops-pinecone',
                    'user-guide/skills/optional/mlops/mlops-pytorch-fsdp',
                    'user-guide/skills/optional/mlops/mlops-pytorch-lightning',
                    'user-guide/skills/optional/mlops/mlops-qdrant',
                    'user-guide/skills/optional/mlops/mlops-saelens',
                    'user-guide/skills/optional/mlops/mlops-simpo',
                    'user-guide/skills/optional/mlops/mlops-slime',
                    'user-guide/skills/optional/mlops/mlops-stable-diffusion',
                    'user-guide/skills/optional/mlops/mlops-tensorrt-llm',
                    'user-guide/skills/optional/mlops/mlops-torchtitan',
                    'user-guide/skills/optional/mlops/mlops-training-trl-fine-tuning',
                    'user-guide/skills/optional/mlops/mlops-training-unsloth',
                    'user-guide/skills/optional/mlops/mlops-whisper',
                  ],
                },
                {
                  type: 'category',
                  label: 'payments',
                  key: 'skills-optional-payments',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/payments/payments-mpp-agent',
                    'user-guide/skills/optional/payments/payments-stripe-link-cli',
                    'user-guide/skills/optional/payments/payments-stripe-projects',
                  ],
                },
                {
                  type: 'category',
                  label: 'productivity',
                  key: 'skills-optional-productivity',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/productivity/productivity-canvas',
                    'user-guide/skills/optional/productivity/productivity-here-now',
                    'user-guide/skills/optional/productivity/productivity-memento-flashcards',
                    'user-guide/skills/optional/productivity/productivity-shop',
                    'user-guide/skills/optional/productivity/productivity-shopify',
                    'user-guide/skills/optional/productivity/productivity-siyuan',
                    'user-guide/skills/optional/productivity/productivity-telephony',
                  ],
                },
                {
                  type: 'category',
                  label: 'research',
                  key: 'skills-optional-research',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/research/research-bioinformatics',
                    'user-guide/skills/optional/research/research-darwinian-evolver',
                    'user-guide/skills/optional/research/research-domain-intel',
                    'user-guide/skills/optional/research/research-drug-discovery',
                    'user-guide/skills/optional/research/research-duckduckgo-search',
                    'user-guide/skills/optional/research/research-gitnexus-explorer',
                    'user-guide/skills/optional/research/research-osint-investigation',
                    'user-guide/skills/optional/research/research-parallel-cli',
                    'user-guide/skills/optional/research/research-qmd',
                    'user-guide/skills/optional/research/research-scrapling',
                    'user-guide/skills/optional/research/research-searxng-search',
                  ],
                },
                {
                  type: 'category',
                  label: 'security',
                  key: 'skills-optional-security',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/security/security-1password',
                    'user-guide/skills/optional/security/security-oss-forensics',
                    'user-guide/skills/optional/security/security-sherlock',
                    'user-guide/skills/optional/security/security-web-pentest',
                  ],
                },
                {
                  type: 'category',
                  label: 'software-development',
                  key: 'skills-optional-software-development',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/software-development/software-development-code-wiki',
                    'user-guide/skills/optional/software-development/software-development-rest-graphql-debug',
                    'user-guide/skills/optional/software-development/software-development-subagent-driven-development',
                  ],
                },
                {
                  type: 'category',
                  label: 'web-development',
                  key: 'skills-optional-web-development',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/web-development/web-development-page-agent',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Messaging Platforms',
      collapsed: true,
      items: [
        'user-guide/messaging/index',
        {
          type: 'category',
          label: 'Popular',
          items: [
            'user-guide/messaging/telegram',
            'user-guide/messaging/discord',
            'user-guide/messaging/slack',
            'user-guide/messaging/whatsapp',
            'user-guide/messaging/whatsapp-cloud',
            'user-guide/messaging/signal',
            'user-guide/messaging/email',
            'user-guide/messaging/sms',
          ],
        },
        {
          type: 'category',
          label: 'Microsoft 365',
          items: [
            'user-guide/messaging/teams',
            'user-guide/messaging/teams-meetings',
            'user-guide/messaging/msgraph-webhook',
          ],
        },
        {
          type: 'category',
          label: 'Chinese platforms',
          items: [
            'user-guide/messaging/dingtalk',
            'user-guide/messaging/feishu',
            'user-guide/messaging/wecom',
            'user-guide/messaging/wecom-callback',
            'user-guide/messaging/weixin',
            'user-guide/messaging/qqbot',
            'user-guide/messaging/yuanbao',
          ],
        },
        {
          type: 'category',
          label: 'Other',
          items: [
            'user-guide/messaging/homeassistant',
            'user-guide/messaging/mattermost',
            'user-guide/messaging/matrix',
            'user-guide/messaging/bluebubbles',
            'user-guide/messaging/photon',
            'user-guide/messaging/google_chat',
            'user-guide/messaging/line',
            'user-guide/messaging/simplex',
            'user-guide/messaging/ntfy',
            'user-guide/messaging/open-webui',
            'user-guide/messaging/webhooks',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        'integrations/index',
        'integrations/nous-portal',
        'integrations/providers',
        'user-guide/features/mcp',
        'user-guide/features/acp',
        'user-guide/features/provider-routing',
        'user-guide/features/fallback-providers',
        'user-guide/features/credential-pools',
      ],
    },
    {
      type: 'category',
      label: 'Guides & Tutorials',
      collapsed: true,
      items: [
        'guides/run-nemotron-3-ultra-free',
        'guides/run-hermes-with-nous-portal',
        'guides/tips',
        'guides/local-llm-on-mac',
        'guides/daily-briefing-bot',
        'guides/team-telegram-assistant',
        'guides/python-library',
        'guides/use-mcp-with-hermes',
        'guides/use-soul-with-hermes',
        'guides/use-voice-mode-with-hermes',
        'guides/build-a-hermes-plugin',
        'guides/automate-with-cron',
        'guides/cron-script-only',
        'guides/automation-blueprints',
        'guides/cron-troubleshooting',
        'guides/work-with-skills',
        'guides/delegation-patterns',
        'guides/github-pr-review-agent',
        'guides/webhook-github-pr-review',
        'guides/migrate-from-openclaw',
        'guides/aws-bedrock',
        'guides/azure-foundry',
        'guides/xai-grok-oauth',
        'guides/oauth-over-ssh',
        'guides/microsoft-graph-app-registration',
        'guides/operate-teams-meeting-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: true,
      items: [
        'developer-guide/contributing',
        {
          type: 'category',
          label: 'Architecture',
          items: [
            'developer-guide/architecture',
            'developer-guide/agent-loop',
            'developer-guide/prompt-assembly',
            'developer-guide/context-compression-and-caching',
            'developer-guide/gateway-internals',
            'developer-guide/session-storage',
            'developer-guide/provider-runtime',
            'developer-guide/programmatic-integration',
          ],
        },
        {
          type: 'category',
          label: 'Extending',
          items: [
            'developer-guide/adding-tools',
            'developer-guide/adding-providers',
            'developer-guide/adding-platform-adapters',
            'developer-guide/memory-provider-plugin',
            'developer-guide/context-engine-plugin',
            'developer-guide/model-provider-plugin',
            'developer-guide/image-gen-provider-plugin',
            'developer-guide/video-gen-provider-plugin',
            'developer-guide/web-search-provider-plugin',
            'developer-guide/plugin-llm-access',
            'developer-guide/creating-skills',
            'developer-guide/extending-the-cli',
          ],
        },
        {
          type: 'category',
          label: 'Internals',
          items: [
            'developer-guide/tools-runtime',
            'developer-guide/browser-supervisor',
            'developer-guide/acp-internals',
            'developer-guide/cron-internals',
            'developer-guide/trajectory-format',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Command Reference',
          items: [
            'reference/cli-commands',
            'reference/slash-commands',
            'reference/profile-commands',
          ],
        },
        {
          type: 'category',
          label: 'Configuration Reference',
          items: [
            'reference/environment-variables',
            'reference/mcp-config-reference',
            'reference/model-catalog',
          ],
        },
        {
          type: 'category',
          label: 'Tools & Skills Reference',
          items: [
            'reference/tools-reference',
            'reference/toolsets-reference',
            'reference/skills-catalog',
            'reference/optional-skills-catalog',
          ],
        },
        'reference/faq',
      ],
    },
  ],
};

export default sidebars;
